name: Metrics
on:
  schedule: [ { cron: "0 7 * * 0" } ]
  workflow_dispatch:
  push: { branches: [ "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # optimize svg size
          optimize: css, xml

          user: yuxqiu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_ignored: css, less, cmake, ejs, makefile, scss
          plugin_traffic: yes
