name: Metrics
on:
  schedule: [ { cron: "0 7 * * 0" } ]
  workflow_dispatch:
  push: { branches: [ "main" ] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          committer_message: "chore: update metrics"
          config_display: large

          user: yuxqiu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_categories: programming
          plugin_languages_ignored: html, css, less, scss, ejs, dockerfile, makefile, cmake

          plugin_traffic: yes

          plugin_achievements: yes
          plugin_achievements_display: compact
