on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.STATS }}
      - name: Update Recent Activity and Push
        uses: jamesgeorge007/github-activity-readme@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.STATS }}
        with:
          COMMIT_MSG: "chore: update README.md"
